apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      hello-world: web
  template:
    metadata: 
      labels:
        hello-world: web
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/theparticleman/helloworldhtml:main
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/environment.txt
          name: environment-volume
      volumes:
      - name: environment-volume
        hostPath:
          path: /src/environment.staging.txt
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    hello-world: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001